In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [7]:
a.shape

(3,)

In [8]:
a = np.arange(15).reshape(3,5)

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
a.dtype

dtype('int32')

In [12]:
a.size

15

In [13]:
# List can execute each element, array execute all

In [14]:
n = 1
m = 2

p = n + m
p

3

In [15]:
a = [1,2,3]
b = [10,20,30]
c = a + b
c

[1, 2, 3, 10, 20, 30]

In [16]:
c = a - b
c

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
a1 = np.array([1,2,3])
b1 = np.array([10,20,30])

c1 = a1 + b1
c1

array([11, 22, 33])

In [18]:
import pandas as pd

In [19]:
data = {'Animal': ['Dog',  'Orangutan', 'Eagle','Pandas', "Elephant"],
        'Name': ['Ellen',  'Adam',  'Joe', 'Eve','Eve'],
        'Legs': [4, 2, 1, 3,4],
        'IsNice': [1,0,0,0,1]}

df = pd.DataFrame(data, columns=['Animal', 'Name', 'Legs', 'IsNice'])

In [23]:
df[1:]

Animal  Name  Legs  IsNice
1  Orangutan  Adam     2       0
2      Eagle   Joe     1       0
3     Pandas   Eve     3       0
4   Elephant   Eve     4       1

In [24]:
df.loc[2]

Animal    Eagle
Name        Joe
Legs          1
IsNice        0
Name: 2, dtype: object

In [25]:
df.iloc[[0],[0]]

Animal
0    Dog

In [26]:
df.iloc[[0, 2, 3]]

Animal   Name  Legs  IsNice
0     Dog  Ellen     4       1
2   Eagle    Joe     1       0
3  Pandas    Eve     3       0

In [27]:
df.loc[[0], ['Name']]

Name
0  Ellen

In [30]:
df.describe(include = 'all')       # exploratory analyst

Animal Name     Legs    IsNice
count       5    5  5.00000  5.000000
unique      5    4      NaN       NaN
top       Dog  Eve      NaN       NaN
freq        1    2      NaN       NaN
mean      NaN  NaN  2.80000  0.400000
std       NaN  NaN  1.30384  0.547723
min       NaN  NaN  1.00000  0.000000
25%       NaN  NaN  2.00000  0.000000
50%       NaN  NaN  3.00000  0.000000
75%       NaN  NaN  4.00000  1.000000
max       NaN  NaN  4.00000  1.000000

In [31]:
# concat just add second df following the first df
# merge is like databse inner join based on a common variable

In [33]:
# SELECT * FROM df WHERE Legs > 2;
df[df['Legs'] > 2]

Animal   Name  Legs  IsNice
0       Dog  Ellen     4       1
3    Pandas    Eve     3       0
4  Elephant    Eve     4       1

In [34]:
# SELECT Animal, Legs FROM df WHERE Legs > 2 and Name = 'Eve';
df[(df['Legs'] > 2) & (df['Name'] == 'Eve')][['Animal', 'Legs']]

Animal  Legs
3    Pandas     3
4  Elephant     4

In [35]:
# SELECT * FROM df WHERE Legs IN (4,2);
df[df['Legs'].isin([4,2])]

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
1  Orangutan   Adam     2       0
4   Elephant    Eve     4       1

In [36]:
df[(df['Name'] == 'Eve') | (df['Name'] == 'Allen')][['Legs']]

Legs
3     3
4     4

In [37]:
df['Flock'] = df['Legs']*12

In [38]:
df

Animal   Name  Legs  IsNice  Flock
0        Dog  Ellen     4       1     48
1  Orangutan   Adam     2       0     24
2      Eagle    Joe     1       0     12
3     Pandas    Eve     3       0     36
4   Elephant    Eve     4       1     48

In [39]:
df = df.drop(['Name'], axis=1)

In [40]:
df

Animal  Legs  IsNice  Flock
0        Dog     4       1     48
1  Orangutan     2       0     24
2      Eagle     1       0     12
3     Pandas     3       0     36
4   Elephant     4       1     48

In [41]:
def yes_no_recode(value):
    recoded = np.where(value == 1, 'Yes', 'No')
    return recoded

df["IsNiceRecoded"] = df["IsNice"].apply(yes_no_recode)

In [42]:
df

Animal  Legs  IsNice  Flock IsNiceRecoded
0        Dog     4       1     48           Yes
1  Orangutan     2       0     24            No
2      Eagle     1       0     12            No
3     Pandas     3       0     36            No
4   Elephant     4       1     48           Yes